### ISSUE TITLE
Error in "blocks" field.

### ISSUE THREAD

**Issue by chrfickinger** [rasteiner/k3-whenquery#13]
I get an error with the latest release by using `type: blocks` in my blueprint. See attatched screenshot:

<img width="791" alt="screenshot" src="https://user-images.githubusercontent.com/91317/193020215-db79bd89-2d73-4d8a-b307-ab35d406452e.png">

**Comment by rasteiner** [comment]
Thanks, should be fixed in 0.4.1 (for kirby 3.8) / 0.3.1 (for kirby 3.7)
