### ISSUE TITLE
Obsolete link in Kirby's panel system view

### ISSUE THREAD

**Issue by grommas** [rasteiner/k3-whenquery#14]
Hi Roman

As the title already describes briefly, the link inside Kirby's panel system view is obsolete. It should direct to [getkirby.com/plugins/rasteiner/whenquery](https://getkirby.com/plugins/rasteiner/whenquery) instead of [rasteiner/k3-whenquery](https://getkirby.com/plugins/rasteiner/k3-whenquery).

Thank you for your work and all the best from Bremen
Jakob

**Comment by rasteiner** [comment]
Thanks for the PR :)
