### ISSUE TITLE
How to access file properties of a neighboring file field?

### ISSUE THREAD

**Issue by owzim** [rasteiner/k3-whenquery#17]
Tried these within the blocks field with a file field called `image`:

* `whenQuery: image ::count($.extension = 'svg') > 0`
* `whenQuery: image ::count($._extension = 'svg') > 0`
* `whenQuery: image.extension = 'svg'`
* `whenQuery: image._extension = 'svg'`

**Comment by rasteiner** [comment]
For files fields the available properties are like these:
<img width="773" alt="image" src="https://github.com/rasteiner/k3-whenquery/assets/6684137/6c4a31e9-6038-4b1a-88bc-874386e5238b">
(you can find out about these properties by running `panel.app.$store.getters["content/values"]()` in the browser JS console.)


So your best bet to "check whether there is an svg file" would probably be to look for the `.svg` string in the filename.

```yaml
whenQuery: "image ::any($.filename =~ '.svg')"
``` 
Currently there is no "ends with" operator. I guess that would be ideal here...

**Comment by rasteiner** [comment]
So, I've added support for regular expressions in the search operator, therefore in version 0.5 you can now write:

```yml
whenQuery: >
  image ::any($.filename =~ /\.svg$/i)
```

This would correctly match stuff like `image.svg`, as well as `image.SVG`, but not `not.an.svg.jpg`.

**Comment by owzim** [comment]
#nice thanks @rasteiner
