### ISSUE TITLE
[K4] Accessing Kirby components

### ISSUE THREAD

**Issue by rasteiner** [rasteiner/k3-whenquery#19]
## **The `use` plugins seem to be run before the Kirby components have been registered**.

This plugin relied on the following pattern:

In a `use` extension:
```ts
const options = Vue.component(type).options;
Vue.component(type, {
  extends: options,
  // my stuff
});
```

In Kirby 4, however, `Vue.component(type)` always seems to return `undefined`. 

## Workaround
Defer the execution to the next javascript tick, at that point the components are accessible.
```ts
setTimeout(() => {
  const options = Vue.component(type).options;
  Vue.component(type, {
    extends: options,
    // my stuff
  });
}, 0);
```

**Comment by rasteiner** [comment]
probably duplicate of https://github.com/getkirby/kirby/issues/5183

**Comment by distantnative** [comment]
Yes, would expect this to be solved with https://github.com/getkirby/kirby/pull/5202 as well

**Comment by rasteiner** [comment]
fixed in alpha 2
