### ISSUE TITLE
Feature Request: `::count()` without expression

### ISSUE THREAD

**Issue by owzim** [rasteiner/k3-whenquery#3]
Hi,

this plugins is a very welcome addition to the kirby panel.

Just to get the count of elements, without filtering them, it would be great to be able to skip the expression between the apprentices.

In fact I don't seem to get the count at all even with `items::count(true = true)`.

**Comment by rasteiner** [comment]
you could use `items.length` :)

`items ::count(true = true)` as well as `items ::count(true)` or `items ::count(1)` should work however... Are you sure `items` is an array? Are there any messages in the console? 
I've just written a test case and it completes.

**Comment by rasteiner** [comment]
Though I agree that `::count()` could be quite idiomatic.

**Comment by rasteiner** [comment]
Should be fixed in v0.2 - could you test that? 
You'd have to download the v0.2 tag: https://github.com/rasteiner/k3-whenquery/archive/refs/tags/0.2.0.zip

**Comment by owzim** [comment]
Working great!

> you could use `items.length` :)

Neither this nor `::count(true = true)` was not working, because I was testing it within the builder field (see #4).  

Everything looking good now in `v0.2`

**Comment by rasteiner** [comment]
Should be available now. 

(After many, many many many commits because packagist didn't want to update because of a version mismatch between files and tags - then I realized I was updating the version in `package.json` instead of `composer.json` 🤦)
