### ISSUE TITLE
`::count()` not working in builder field

### ISSUE THREAD

**Issue by owzim** [rasteiner/k3-whenquery#4]
https://github.com/TimOetting/kirby-builder

I am not sure if `whenquery` is working at all in the builder field.

From a quick glance at the code it does not seems so, since it is refercning the content of the page as context.

https://github.com/rasteiner/k3-whenquery/blob/86f55111fb018f8765c8526f560f09a7c3fcba1f/src/index.ts#L22

**Comment by rasteiner** [comment]
have tested it in blocks field (which should be the same problem). 
Could you test it in the builder? 

You'd have to download the [v0.2 tag](https://github.com/rasteiner/k3-whenquery/tree/0.2.0):  https://github.com/rasteiner/k3-whenquery/archive/refs/tags/0.2.0.zip

**Comment by owzim** [comment]
Working great now, thanks!

When will this update be available through composer?
