### ISSUE TITLE
Hide section based on page

### ISSUE THREAD

**Issue by bogdancondorachi** [rasteiner/k3-whenquery#6]
I have a template with a subpage section. I wanna hide that section on pages like Home or Kontakt.
I wonder if it can be done with this plugin and how.

Thanks :)

**Comment by rasteiner** [comment]
Hello :)

the name of the page template isn't accessible, and enabling that would add a whole new set of syntax (we would need to distinguish between "page properties" and "page content"), and I'm not sure this feature would be worth its complexity. 

I'd suggest to use different blueprints for your Home and Kontakt pages, I think that would be the easiest.
